name: Docker Image CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME }}/ku-hackathon:test --build-arg GOOGLE_SERVICE_ACCOUNT_EMAIL="${{secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL}}" --build-arg GOOGLE_SHEET_ISSUES="${{secrets.GOOGLE_SHEET_ISSUES}}" --build-arg GOOGLE_SHEET_DEV_FORM="${{secrets.GOOGLE_SHEET_DEV_FORM}}" --build-arg GOOGLE_SHEET_DESIGN_FORM="${{secrets.GOOGLE_SHEET_DESIGN_FORM}}" --build-arg GOOGLE_PRIV_KEY="${{secrets.GOOGLE_PRIV_KEY}}" .

      - name: Push the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ku-hackathon:test
